development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dev_city_app
  pool: 5
  username: root
  password: qwerty
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: prod_city_app
  pool: 5
  username: 
  password: