development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dev_city_app
  pool: 5
  username: root
  password: qwerty
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: prod_city_app
  pool: 5
  username: root
  password: qwerty
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_city_app
  pool: 5
  username: root
  password: qwerty
  host: localhost